In [29]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import re
from sqlalchemy import create_engine

In [30]:
df=pd.read_csv("Luxury_Housing_Bangalore.csv")
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [31]:
for c in df.columns:
    if df[c].dtype == object:
        df[c] = df[c].astype(str).str.strip()
        df.loc[df[c] == "nan", c] = np.nan
        df.loc[df[c] == "", c] = np.nan

In [32]:
df["Micro_Market"].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [33]:
df["Micro_Market"]=df["Micro_Market"].replace({"SARJAPUR ROAD":"Sarjapur Road",
                                               "sarjapur road":"Sarjapur Road",
                                               "indiranagar":"Indiranagar",
                                               "INDIRANAGAR":"Indiranagar",
                                               "BANNERGHATTA ROAD":"Bannerghatta Road",
                                               "bannerghatta road":"Bannerghatta Road",
                                               "bellary road":"Bellary Road",
                                               "BELLARY ROAD":"Bellary Road",
                                               "koramangala":"Koramangala",
                                               "KORAMANGALA":"Koramangala",
                                               "YELAHANKA":"Yelahanka",
                                               "yelahanka":"Yelahanka",
                                               "whitefield":"Whitefield",
                                               "WHITEFIELD":"Whitefield",
                                               "jp nagar":"JP Nagar",
                                               "JP NAGAR":"JP Nagar",
                                               "jp nagar":"JP Nagar",
                                               "Jp Nagar":"JP Nagar",
                                               "rajajinagar":"Rajajinagar",
                                               "RAJAJINAGAR":"Rajajinagar",
                                               "jayanagar":"Jayanagar",
                                               "JAYANAGAR":"Jayanagar",
                                               "DOMLUR":"Domlur",
                                               "domlur":"Domlur",
                                               "Mg Road":"MG Road",
                                               "mg road":"MG Road",
                                               "MG ROAD":"MG Road",
                                               "HENNUR ROAD":"Hennur Road",
                                               "hennur road":"Hennur Road",
                                               "electronic city":"Electronic City",
                                               "ELECTRONIC CITY":"Electronic City",
                                               "HEBBAL":"Hebbal",
                                               "hebbal":"Hebbal",
                                               "KANAKAPURA ROAD":"Kanakapura Road",
                                               "kanakapura road":"Kanakapura Road",
                                                })

In [34]:
df["Project_Name"]=df["Project_Name"].astype(str).str.strip("Project_").astype(int)

In [35]:
df["Developer_Name"].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [36]:
df["Configuration"].unique()

array(['4bhk', '3Bhk', '3BHK', '4Bhk', '5BHK+', '4BHK', '5bhk+', '5Bhk+',
       '3bhk'], dtype=object)

In [37]:
df["Configuration"]=df["Configuration"].replace({"4bhk":"4BHK",
                                                 "3Bhk":"3BHK",
                                                 "4Bhk":"4BHK",
                                                 "5bhk+":"5BHK+",
                                                 "5Bhk+":"5BHK+",
                                                 "3bhk":"3BHK"})

In [38]:
df["Buyer_Comments"] = df["Buyer_Comments"].fillna("No comment")

In [39]:
def parse_ticket_price_cr(v):
    """Parse messy ticket price values and return in Crores (float)."""
    if pd.isna(v):
        return np.nan
    s = str(v).replace(",", "").replace("₹", "").strip().lower()
    if s == "":
        return np.nan

    # Regex to capture number + optional unit
    m = re.match(r'^([0-9]+(?:\.[0-9]+)?)\s*([a-zA-Z]*)$', s)
    if m:
        num = float(m.group(1))
        unit = m.group(2)

        # Explicit units
        if "cr" in unit or "crore" in unit:
            return num
        if "lakh" in unit or "lac" in unit:
            return num / 100.0

        # No unit given → apply your rule
        if "." in m.group(1):   # decimal present → Crores
            return num
        else:                   # integer only → Lakhs
            return num / 100.0

    # Fallback: try extracting numbers anyway
    nums = re.findall(r'[\d\.]+', s)
    if not nums:
        return np.nan
    num_str = nums[0]
    num = float(num_str)
    if "." in num_str:
        return num  # decimal → Crores
    else:
        return num / 100.0  # integer → Lakhs

df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].apply(parse_ticket_price_cr)
df["Ticket_Price_Cr"] = pd.to_numeric(df["Ticket_Price_Cr"], errors="coerce")

In [40]:
df["Unit_Size_Sqft"] = pd.to_numeric(df["Unit_Size_Sqft"], errors="coerce")
df.loc[df["Unit_Size_Sqft"] <= 0, "Unit_Size_Sqft"] = np.nan

In [41]:
for col in ["Amenity_Score", "Connectivity_Score", "Locality_Infra_Score"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [42]:
a=LabelEncoder()
df.loc[:,"NRI_Buyer"] = a.fit_transform(df["NRI_Buyer"])

In [43]:
df["Purchase_Quarter"]=pd.to_datetime(df["Purchase_Quarter"],format="%Y-%m-%d")
df["Quarter_Year"] = df["Purchase_Quarter"].dt.to_period("Q").astype(str)
df["Quarter_Number"] = df["Purchase_Quarter"].dt.quarter.astype(int)
df["Purchase_Year"] = df["Purchase_Quarter"].dt.year.astype(int)

In [44]:
df["Amenity_Score"] = df.groupby("Micro_Market")["Amenity_Score"]\
                        .transform(lambda x: x.fillna(x.median()))
df["Amenity_Score"] = df["Amenity_Score"].fillna(df["Amenity_Score"].median())

In [45]:
df["Unit_Size_Sqft"] = df.groupby("Configuration")["Unit_Size_Sqft"]\
                         .transform(lambda x: x.fillna(x.median()))
df["Unit_Size_Sqft"] = df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].median())

In [46]:
# Step 1: Calculate Price per Sqft (in INR) where both values exist
df["Price_per_Sqft_INR"] = (df["Ticket_Price_Cr"] * 1e7) / df["Unit_Size_Sqft"]

# Step 2: Compute median Price/Sqft for each Micro_Market
pps_market = df.groupby("Micro_Market")["Price_per_Sqft_INR"].median()

# Step 3: Define imputation function
def impute_ticket_price(row):
    if pd.isna(row["Ticket_Price_Cr"]) and pd.notna(row["Unit_Size_Sqft"]):
        # Look up median price per sqft for this market
        market_pps = pps_market.get(row["Micro_Market"], np.nan)
        if pd.notna(market_pps):
            return (row["Unit_Size_Sqft"] * market_pps) / 1e7  # back to Crores
    return row["Ticket_Price_Cr"]

# Step 4: Apply row-wise imputation
df["Ticket_Price_Cr"] = df.apply(impute_ticket_price, axis=1)

# Step 5: Fill any remaining NaN with global median (as last fallback)
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].fillna(df["Ticket_Price_Cr"].median())

In [47]:
if "Transaction_Type" in df.columns:
    txn = df["Transaction_Type"].astype(str).str.lower()
    df["Booking_Status"] = np.where(txn == "primary", "Booked",
                                    np.where(txn == "secondary", "Resale", "Unknown"))
    df["Booking_Flag"] = np.where(df["Booking_Status"] == "Booked", 1, 0).astype(int)

# Price per sqft in INR: 1 Crore = 10,000,000 INR
df["Price_per_Sqft_INR"] = (df["Ticket_Price_Cr"] * 10_000_000) / df["Unit_Size_Sqft"]
df["Price_per_Sqft_INR"] = df["Price_per_Sqft_INR"].replace([np.inf, -np.inf], np.nan)
df.loc[df["Price_per_Sqft_INR"] <= 0, "Price_per_Sqft_INR"] = np.nan

In [48]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Quarter_Year,Quarter_Number,Purchase_Year,Price_per_Sqft_INR,Booking_Status,Booking_Flag
0,PROP000001,Sarjapur Road,0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,1,9.212491,18,Loved the amenities!,2025Q1,1,2025,31679.120594,Booked,1
1,PROP000002,Indiranagar,1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,0,7.723898,106,No comment,2024Q2,2,2024,28284.985887,Booked,1
2,PROP000003,Bannerghatta Road,2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,1,6.985493,113,Agent was not responsive.,2023Q4,4,2023,13646.976013,Booked,1
3,PROP000004,Bellary Road,3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,1,6.100929,106,Excellent location!,2024Q1,1,2024,15175.012103,Booked,1
4,PROP000005,Koramangala,4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,0,5.312510,18,Too far from my office.,2024Q4,4,2024,21471.096187,Resale,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,Bellary Road,229,Embassy,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,...,0,7.511827,22,Will buy after possession.,2024Q4,4,2024,13258.612265,Resale,0
100996,PROP059810,Bellary Road,309,Brigade,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,...,0,9.851849,26,Agent was not responsive.,2024Q3,3,2024,31776.329690,Booked,1
100997,PROP065099,Hennur Road,98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,...,0,9.101604,44,Loved the amenities!,2023Q4,4,2023,23839.912923,Booked,1
100998,PROP093022,Rajajinagar,21,Embassy,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,...,1,8.588551,66,Excellent location!,2024Q2,2,2024,14679.430230,Resale,0
100999,PROP023826,Whitefield,325,L&T Realty,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,...,1,9.917647,58,Loved the amenities!,2023Q4,4,2023,41236.793039,Booked,1

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  int64
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        101000 non-null  float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       101000 non-null  float64
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  datetime64[ns]
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         101000 non-null  float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        101000 non-null  object
 18  Quarter_Year          101000 non-null  object
 19  Quarter_Number        101000 non-null  int64
 20  Purchase_Year         101000 non-null  int64
 21  Price_per_Sqft_INR    101000 non-null  float64
 22  Booking_Status        101000 non-null  object
 23  Booking_Flag          101000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(5), object(12)
memory usage: 18.5+ MB

In [50]:
dup_before = df.shape[0]
df = df.drop_duplicates(subset=["Property_ID", "Developer_Name", "Project_Name", "Configuration", "Unit_Size_Sqft"])
dup_after = df.shape[0]
print(f"Dropped duplicates: {dup_before - dup_after}")

Dropped duplicates: 1000

In [56]:
engine = create_engine('mysql+mysqlconnector://root:Welcome123@127.0.0.1:3306/Housing')

In [57]:
df.to_sql('housing_analysis',con=engine,if_exists='replace',index=False)

100000